;,Tile,index,$000
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$001
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FE,$FF,$FE,$01,$FD,$FE,$FC
;,Tile,index,$002
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$7F,$FF,$7F
;,Tile,index,$003
    db $01,$FF,$FE,$FE,$00,$FC,$FF,$FC,$00,$F8,$FF,$F8,$00,$F0,$FF,$F0,$00,$E0,$FF,$E0,$00,$C0,$FF,$C0,$00,$80,$FF,$80,$01,$E1,$1E,$E0
;,Tile,index,$004
    db $FE,$FF,$01,$01,$FF,$FF,$00,$00,$7F,$7C,$80,$00,$38,$27,$C7,$07,$20,$3F,$DF,$1F,$40,$7F,$BF,$3F,$80,$FF,$7F,$7F,$00,$CF,$FF,$CF
;,Tile,index,$005
    db $00,$FF,$FF,$FF,$E0,$DF,$1F,$1F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$006
    db $02,$FA,$FD,$F8,$05,$F5,$FA,$F0,$0A,$EA,$F5,$E0,$15,$D5,$EA,$C0,$6B,$EB,$94,$80,$3E,$8E,$C1,$80,$23,$9C,$DD,$9D,$66,$18,$9B,$1A
;,Tile,index,$007
    db $80,$BF,$7F,$3F,$40,$5F,$BF,$1F,$A0,$AF,$5F,$0F,$50,$57,$AF,$07,$FC,$FF,$03,$03,$AA,$01,$FF,$AB,$57,$00,$FC,$54,$AF,$00,$F8,$A8
;,Tile,index,$008
    db $50,$5E,$A1,$0E,$AB,$AB,$54,$00,$55,$54,$AA,$00,$AB,$AA,$54,$00,$56,$D4,$A9,$80,$2A,$A8,$D5,$80,$5D,$DF,$A0,$82,$FA,$75,$0A,$0F
;,Tile,index,$009
    db $08,$17,$E7,$17,$1C,$1B,$E3,$03,$1E,$3D,$C1,$21,$1F,$1E,$E0,$00,$3F,$38,$C6,$06,$3C,$03,$CC,$0F,$2F,$00,$DF,$0F,$D7,$80,$3F,$17
;,Tile,index,$00A
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$7F,$FF,$80,$7F,$9F,$FF,$E0,$1F,$E7,$FF
;,Tile,index,$00B
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FF,$05,$FA,$FA,$FF,$0F,$F0,$F0,$FF,$59,$A6,$A0,$FF,$A8,$57,$00,$FF
;,Tile,index,$00C
    db $01,$FE,$FE,$FF,$06,$F9,$F8,$FF,$AA,$55,$54,$FF,$55,$AA,$08,$FF,$0A,$F5,$00,$FF,$2D,$D2,$00,$FF,$94,$6B,$00,$FF,$00,$FF,$00,$FF
;,Tile,index,$00D
    db $80,$7F,$7F,$FF,$60,$9F,$1F,$FF,$10,$EF,$0F,$FF,$21,$DE,$1E,$FF,$4A,$B5,$34,$FF,$3E,$C1,$00,$FF,$0A,$F5,$04,$FF,$04,$FB,$00,$FF
;,Tile,index,$00E
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$80,$7F,$7F,$FF,$40,$BF,$3F,$FF,$2C,$D3,$13,$FF,$34,$CB,$03,$FF,$62,$9D,$01,$FF
;,Tile,index,$00F
    db $4D,$30,$B7,$35,$4A,$30,$B7,$32,$15,$60,$EF,$65,$0A,$E0,$FF,$EA,$35,$C0,$DF,$D5,$0A,$F0,$CF,$FA,$01,$CC,$F3,$CD,$00,$C2,$FD,$C2
;,Tile,index,$010
    db $57,$00,$F8,$50,$AF,$00,$F0,$A0,$5F,$00,$E0,$40,$A7,$18,$F8,$B8,$5F,$3A,$E0,$60,$8F,$6D,$F0,$E0,$17,$56,$E8,$40,$2B,$EB,$D4,$C0
;,Tile,index,$011
    db $FE,$00,$3F,$3E,$F8,$00,$FF,$F8,$E0,$80,$7F,$60,$80,$00,$7F,$00,$80,$00,$7F,$00,$C0,$00,$3F,$00,$C0,$80,$3F,$00,$E0,$40,$1F,$00
;,Tile,index,$012
    db $EB,$80,$3F,$2B,$55,$00,$BF,$15,$6A,$40,$BF,$2A,$14,$03,$FF,$17,$20,$3F,$DF,$1F,$00,$1F,$FF,$1F,$10,$1F,$EF,$0F,$00,$0F,$FF,$0F
;,Tile,index,$013
    db $F8,$07,$F9,$FF,$FE,$01,$F1,$F1,$FE,$01,$81,$81,$3E,$C1,$C1,$C1,$1E,$E1,$E1,$E1,$1E,$F1,$E1,$E1,$1E,$EB,$E1,$E1,$1E,$F5,$E1,$E1
;,Tile,index,$014
    db $40,$BF,$80,$FF,$A0,$5F,$00,$FF,$40,$BF,$80,$FF,$30,$CF,$C0,$FF,$14,$EB,$E0,$FF,$22,$DD,$C0,$FF,$15,$EA,$E2,$FF,$08,$F7,$F7,$FF
;,Tile,index,$015
    db $00,$FF,$00,$FF,$00,$FF,$00,$FF,$40,$BF,$00,$FF,$E0,$1F,$00,$FF,$44,$BB,$00,$FF,$A8,$57,$40,$FF,$15,$EA,$E8,$FF,$02,$FD,$FD,$FF
;,Tile,index,$016
    db $00,$FF,$00,$FF,$06,$F9,$00,$FF,$01,$FE,$00,$FF,$12,$ED,$00,$FF,$0D,$F2,$02,$FF,$84,$7B,$03,$FF,$74,$8B,$03,$FF,$88,$77,$77,$FF
;,Tile,index,$017
    db $43,$BC,$00,$FF,$E6,$19,$01,$FF,$A4,$5B,$43,$FF,$9C,$63,$63,$FF,$08,$F7,$F7,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$018
    db $00,$C1,$FF,$C1,$02,$C3,$FD,$C1,$02,$C1,$FD,$C1,$04,$C7,$FB,$C3,$04,$C2,$FB,$C2,$08,$CE,$F7,$C6,$08,$C4,$F7,$C4,$10,$DC,$EF,$CC
;,Tile,index,$019
    db $54,$D4,$AB,$80,$20,$A0,$DF,$80,$50,$50,$AF,$00,$A0,$A0,$5F,$00,$41,$41,$BE,$00,$80,$81,$7F,$01,$03,$02,$FD,$01,$00,$03,$FF,$03
;,Tile,index,$01A
    db $E0,$80,$1F,$00,$70,$70,$FF,$70,$30,$30,$FF,$70,$18,$18,$FF,$F8,$09,$09,$FE,$F8,$47,$47,$B8,$F8,$DF,$CF,$B8,$F8,$5F,$5F,$BC,$FC
;,Tile,index,$01B
    db $08,$0F,$F7,$07,$00,$07,$FF,$07,$18,$1F,$E7,$07,$78,$7F,$87,$07,$F8,$FF,$07,$07,$F8,$FF,$07,$07,$F8,$FF,$07,$07,$F0,$FF,$0F,$0F
;,Tile,index,$01C
    db $1C,$EB,$E3,$E3,$1C,$F7,$E3,$E3,$18,$EF,$E7,$E7,$18,$F7,$E7,$E7,$10,$EF,$EF,$EF,$10,$FF,$EF,$EF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$01D
    db $10,$C8,$EF,$C8,$20,$D8,$DF,$D8,$04,$FA,$F9,$FA,$02,$FD,$FC,$FD,$03,$FD,$FC,$FC,$01,$FE,$FE,$FE,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$01E
    db $04,$07,$FB,$03,$00,$07,$FF,$07,$09,$0E,$F7,$07,$00,$0F,$FF,$0F,$10,$9F,$6F,$8F,$80,$DF,$3F,$5F,$C1,$7E,$1F,$3F,$E0,$7F,$1F,$1F
;,Tile,index,$01F
    db $C7,$C7,$3C,$FC,$C7,$C7,$3E,$FE,$5F,$4F,$BE,$FE,$DF,$DF,$3F,$FF,$C7,$C7,$3F,$FF,$C7,$C7,$3F,$FF,$5F,$4F,$BF,$FF,$DF,$DF,$3F,$FF
;,Tile,index,$020
    db $F0,$FF,$0F,$0F,$F0,$FF,$0F,$0F,$F0,$FF,$0F,$0F,$F0,$FF,$0F,$0F,$E0,$FF,$1F,$1F,$60,$FF,$9F,$9F,$60,$FF,$9F,$9F,$20,$FF,$DF,$DF
;,Tile,index,$021
    db $60,$BF,$9F,$9F,$30,$DF,$CF,$CF,$30,$DF,$CF,$CF,$18,$EF,$E7,$E7,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$022
    db $3F,$3F,$FF,$FF,$1E,$9F,$FF,$FF,$0C,$CF,$FF,$FF,$14,$F7,$EF,$FF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$30,$F3,$CF,$FF
;,Tile,index,$023
    db $20,$FF,$DF,$DF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
;,Tile,index,$024
    db $14,$F7,$EF,$FF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$04,$E7,$FF,$EF,$30,$F3,$CF,$FF
;,Tile,index,$025
    db $00,$FE,$FE,$FF,$00,$FE,$FE,$FF,$00,$FA,$FA,$FF,$04,$FA,$FE,$FF,$04,$FA,$FE,$FF,$04,$F9,$FD,$FF,$04,$F9,$FD,$FF,$04,$F9,$FD,$FF
;,Tile,index,$026
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$BF,$BF,$00,$FF,$BF,$BF,$00,$FF,$BF,$BF,$00,$FF,$BF,$BF,$00,$FF,$BF,$BF,$00,$FF,$BF,$BF
;,Tile,index,$027
    db $04,$F9,$FD,$FF,$04,$F9,$FD,$FF,$04,$F8,$FC,$FF,$00,$F8,$F8,$FF,$00,$E8,$E8,$FF,$00,$E8,$E8,$FF,$10,$E8,$F8,$FF,$10,$E1,$F1,$FF
;,Tile,index,$028
    db $00,$FF,$BF,$BF,$00,$FF,$BF,$BF,$00,$FF,$BF,$BF,$00,$FF,$DF,$DF,$00,$7F,$5F,$DF,$00,$7F,$1F,$9F,$00,$7F,$1F,$9F,$00,$7F,$1F,$9F
;,Tile,index,$029
    db $10,$E5,$F5,$FF,$10,$E5,$F5,$FF,$11,$E4,$F5,$FF,$19,$E4,$FD,$FF,$19,$E4,$FD,$FF,$08,$E0,$E8,$FF,$08,$A0,$A8,$FF,$00,$A2,$A2,$FF
;,Tile,index,$02A
    db $00,$7F,$1F,$9F,$00,$FF,$8F,$8F,$00,$FF,$8F,$8F,$00,$FF,$8F,$8F,$00,$FF,$8B,$8B,$00,$FF,$BB,$BB,$00,$FF,$B3,$B3,$00,$FF,$B3,$B3
;,Tile,index,$02B
    db $00,$BF,$BF,$FF,$00,$BE,$BE,$FF,$00,$3E,$3E,$FF,$00,$7B,$5B,$DF,$00,$7B,$5B,$DF,$00,$F3,$D3,$DF,$00,$F7,$F7,$FF,$00,$F7,$F7,$FF
;,Tile,index,$02C
    db $40,$92,$D2,$FF,$40,$13,$53,$FF,$40,$15,$55,$FF,$40,$15,$55,$FF,$40,$B5,$F5,$FF,$40,$BD,$FD,$FF,$00,$BD,$BD,$FF,$00,$BD,$BD,$FF
;,Tile,index,$02D
    db $00,$FF,$FF,$FF,$00,$DF,$DF,$FF,$00,$DF,$DE,$FE,$00,$9F,$96,$F6,$00,$BF,$B4,$F4,$00,$FF,$F1,$F1,$00,$FF,$F3,$F3,$00,$FF,$FB,$FB
;,Tile,index,$02E
    db $00,$FF,$B3,$B3,$00,$FF,$F3,$F3,$00,$DF,$D1,$F1,$00,$DF,$D1,$F1,$00,$DF,$D1,$F1,$00,$DF,$D1,$F1,$00,$FF,$FB,$FB,$00,$FF,$FB,$FB
;,Tile,index,$02F
    db $00,$FF,$FF,$FF,$00,$FF,$FD,$FF,$00,$FF,$FF,$FF,$10,$EF,$F1,$EF,$00,$FF,$FF,$FF,$80,$7F,$9F,$7F,$00,$FF,$F7,$FF,$00,$FF,$FF,$FF
;,Tile,index,$030
    db $00,$FF,$BF,$FF,$00,$FF,$FF,$FF,$60,$9F,$E7,$9F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$06,$F9,$FE,$F9,$20,$DF,$3F,$DF,$00,$FF,$FF,$FF
;,Tile,index,$031
    db $00,$FF,$9B,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$30,$CF,$F0,$CF,$00,$FF,$FF,$FF,$00,$FF,$3F,$FF,$06,$F9,$FE,$F9,$30,$CF,$F1,$CF
;,Tile,index,$032
    db $00,$FF,$FF,$FF,$00,$FF,$FE,$FF,$40,$BF,$CF,$BF,$00,$FF,$FF,$FF,$10,$EF,$F1,$EF,$00,$FF,$FF,$FF,$00,$FF,$37,$FF,$00,$FF,$FF,$FF
;,Tile,index,$033
    db $00,$FF,$FF,$FF,$00,$FE,$FF,$FF,$19,$E2,$FF,$FF,$0D,$E0,$FF,$FF,$0B,$E4,$FB,$FF,$05,$F2,$FC,$FE,$06,$80,$FD,$FC,$7D,$80,$FA,$F8
;,Tile,index,$034
    db $80,$7F,$FF,$FF,$80,$3F,$FF,$FF,$CC,$23,$FF,$FF,$58,$83,$7F,$FF,$68,$93,$6F,$FF,$D0,$27,$1F,$3F,$F0,$C0,$1F,$1F,$FF,$00,$0F,$0F
;,Tile,index,$035
    db $00,$FF,$FF,$FF,$00,$FF,$FE,$FF,$00,$FE,$FC,$FF,$00,$C4,$C8,$FF,$10,$D0,$C8,$FF,$00,$C0,$F8,$FF,$00,$E0,$CC,$FF,$01,$C0,$87,$FF
;,Tile,index,$036
    db $37,$8A,$F0,$F8,$0F,$C0,$F8,$F8,$07,$F0,$FC,$FC,$05,$F2,$FC,$FE,$0B,$E4,$FB,$FF,$0E,$E0,$FF,$FF,$18,$E1,$FF,$FF,$00,$E7,$FF,$FF
;,Tile,index,$037
    db $F2,$0C,$03,$0F,$F8,$01,$0F,$0F,$F0,$07,$1F,$1F,$D0,$2F,$1F,$3F,$E8,$17,$6F,$7F,$B8,$07,$7F,$7F,$4C,$03,$BF,$3F,$40,$33,$BF,$3F
;,Tile,index,$038
    db $02,$81,$02,$FF,$02,$81,$02,$FF,$01,$80,$03,$FF,$00,$C0,$84,$FF,$00,$E0,$C8,$FF,$00,$C4,$F8,$FF,$10,$D2,$CC,$FF,$00,$C5,$CE,$FF
;,Tile,index,$039
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$02,$F3,$FD,$F1,$01,$DD,$E2,$DC,$4F,$88,$B0,$80,$32,$C2,$CC,$C0,$0C,$F1,$F1,$F1,$00,$FF,$FF,$FF
;,Tile,index,$03A
    db $40,$3F,$BF,$3F,$40,$3F,$BF,$3F,$60,$27,$9F,$07,$40,$5D,$A3,$1D,$79,$08,$86,$00,$26,$21,$99,$01,$58,$07,$87,$07,$40,$3F,$BF,$3F
;,Tile,index,$03B
    db $00,$FE,$FF,$FE,$01,$FE,$FF,$FF,$01,$FC,$FF,$FD,$03,$FC,$FF,$FF,$03,$F8,$FF,$FB,$61,$B8,$DF,$D9,$71,$B8,$CF,$C9,$35,$98,$EB,$A9
;,Tile,index,$03C
    db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$80,$FF,$7F,$7F,$80,$FF,$7F,$7F,$C0,$FF,$3F,$3F,$C4,$F7,$3B,$33,$CC,$E7,$3B,$2B,$CC,$A7,$3B,$2B
;,Tile,index,$03D
    db $3D,$98,$E3,$A1,$1D,$C8,$F3,$D1,$1D,$C8,$F3,$D1,$0E,$E4,$F9,$E8,$36,$A4,$C9,$80,$DB,$13,$E4,$C0,$2D,$89,$F2,$A0,$07,$F7,$F8,$F0
;,Tile,index,$03E
    db $DC,$8F,$33,$13,$D8,$8F,$37,$17,$F8,$9F,$27,$27,$B0,$3F,$4F,$0F,$B4,$23,$4F,$07,$7E,$47,$99,$19,$FC,$9F,$23,$23,$20,$3F,$DF,$1F
;,Tile,index,$03F
    db $EE,$00,$FF,$EE,$DD,$11,$EE,$CC,$77,$33,$DD,$55,$77,$33,$DD,$55,$77,$33,$DD,$55,$BB,$BB,$FF,$BB,$BB,$BB,$FF,$BB,$FF,$FF,$BB,$BB
;,Tile,index,$040
    db $FF,$FF,$77,$FF,$FF,$FF,$77,$FF,$FF,$FF,$22,$FF,$FF,$FF,$22,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF
;,Tile,index,$041
    db $77,$77,$FF,$FF,$77,$77,$FF,$FF,$22,$22,$FF,$FF,$22,$22,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF
;,Tile,index,$042
    db $00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF
;,Tile,index,$043
    db $FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF

