;,Tile,index,$000
    db $FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF
;,Tile,index,$001
    db $FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FE,$FF,$FF,$00,$F8,$FF,$FF,$00,$F0,$FF,$FF,$00,$E0,$FF,$FF,$00,$E0,$FF,$FF,$00,$C0
;,Tile,index,$002
    db $FF,$FF,$00,$FF,$FF,$FF,$00,$81,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00
;,Tile,index,$003
    db $FF,$FF,$00,$C0,$FF,$FF,$00,$80,$FF,$FF,$00,$80,$FF,$FF,$00,$80,$FF,$FF,$00,$80,$FF,$FF,$00,$80,$FF,$FF,$00,$80,$FF,$FF,$00,$C0
;,Tile,index,$004
    db $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00
;,Tile,index,$005
    db $00,$00,$7E,$81,$00,$00,$BD,$42,$00,$00,$DB,$24,$00,$00,$E7,$18,$00,$00,$E7,$18,$00,$00,$DB,$24,$00,$00,$BD,$42,$00,$00,$7E,$81

